import { Inter } from "next/font/google";
import "./globals.css";
import { UIProvider } from "@/providers/ui-provider";
import { Layout } from "@/components/layout/layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <body
        className={inter.className}
      >
        <UIProvider>
          <Layout>
            {children}
          </Layout>
        </UIProvider>
      </body>
    </html>
  );
}
